# Generated by Django 6.0.4 on 2026-04-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_seed_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
    ]
